# This device/package is used for early SoC bringup.
# Please leave debug options enabled, MediaTek default UART baudrate is 921600.

pmos.nosplash
loglevel=15
clk_ignore_unused
regulator_ignore_unused
keep_bootcon
earlycon=uart8250,mmio32,0x11002000,921600n1
console=ttyS0,921600n1
console=tty0
