# plymouth messes up the screen so badly that a picture never comes up. better show kernel logs
-quiet
-splash

# ttyTitania0 is the UART
console=ttyTitania0

# also enable the on-screen console
console=tty0
